export interface FindingListItem {
  id: number;
  serverProfileId: string;
  serverName: string;
  queryId?: number | null;
  databaseName?: string | null;
  objectName?: string | null;
  scopeText: string;
  ruleId: string;
  ruleName: string;
  category: string;
  categoryLabel: string;
  icon: string;
  severity: number;
  title: string;
  whatWasFound: string;
  whyItMatters: string;
  nextCheck: string;
  technicalDescription: string;
  confidenceScore: number;
  impactScore: number;
  findingScore: number;
  firstDetectedAt: string;
  lastDetectedAt: string;
  resolvedAt?: string | null;
  occurrenceCount: number;
  status: string;
}

export interface RecommendationListItem {
  id: number;
  findingId: number;
  serverProfileId: string;
  serverName: string;
  queryId?: number | null;
  databaseName?: string | null;
  objectName?: string | null;
  scopeText: string;
  ruleId: string;
  ruleName: string;
  category: string;
  categoryLabel: string;
  icon: string;
  severity: number;
  findingTitle: string;
  findingTechnicalDescription: string;
  whatWasFound: string;
  whyItMatters: string;
  priorityScore: number;
  title: string;
  explanation: string;
  expectedBenefit: string;
  riskLevel: string;
  confidenceScore: number;
  recommendedAction: string;
  scriptText?: string | null;
  canExecute: boolean;
  status: string;
  createdAt: string;
}
