<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../SqlServerAdvisor.Domain/SqlServerAdvisor.Domain.csproj" />
    <ProjectReference Include="../SqlServerAdvisor.Application/SqlServerAdvisor.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SqlServer.TransactSql.ScriptDom" Version="180.102.0" />
  </ItemGroup>
</Project>
