namespace SqlServerAdvisor.Application.DTOs;

public sealed record FragmentedIndexDto(
    long Id,
    Guid ServerProfileId,
    string ServerName,
    string DatabaseName,
    string TableName,
    string IndexName,
    string TypeDesc,
    string KeyColumns,
    string IncludeColumns,
    decimal SizeMb,
    long UserSeeks,
    long UserScans,
    long UserLookups,
    long UserUpdates,
    bool HasFilter,
    string? FilterDefinition,
    int UsageSinceDays,
    decimal? AvgFragmentationPercent,
    long? PageCount,
    string DiagnosticLevel,
    string DiagnosticHeadline,
    string DiagnosticSummary,
    string SuggestedInspection,
    DateTimeOffset CapturedAt);

public sealed record MissingIndexDto(
    long Id,
    Guid ServerProfileId,
    string ServerName,
    string DatabaseName,
    string TableName,
    string EqualityColumns,
    string InequalityColumns,
    string IncludedColumns,
    long UserSeeks,
    long UserScans,
    decimal AvgTotalUserCost,
    decimal AvgUserImpact,
    decimal ImprovementMeasure,
    bool CoveredByExistingIndex,
    string DiagnosticLevel,
    string DiagnosticHeadline,
    string DiagnosticSummary,
    string SuggestedInspection,
    DateTimeOffset CapturedAt);
