namespace SqlServerAdvisor.Application.DTOs;

public sealed record StatisticsStatusDto(
    long Id,
    Guid ServerProfileId,
    string ServerName,
    string DatabaseName,
    string TableName,
    string StatisticsName,
    string StatisticsType,
    long Rows,
    long RowsSampled,
    long ModificationCounter,
    decimal ModificationPercent,
    DateTime? LastUpdated,
    decimal? SamplePercent,
    bool AutoCreated,
    bool UserCreated,
    bool NoRecompute,
    bool HasFilter,
    string? FilterDefinition,
    string DiagnosticLevel,
    string DiagnosticHeadline,
    string DiagnosticSummary,
    string SuggestedInspection,
    DateTimeOffset CapturedAt);
